id: my-ig
canonical: https://wrig.corisystem.org
name: WorkReqsIG
title: US HR1 Medicaid Work Requirements IG (proposed, not supported by CMS)
description: Implementation Guide for Medicaid Work Requirements exemptions mapping and examples.
status: draft
version: 0.1.0
fhirVersion: 4.0.1
jurisdiction:
  - coding:
      - system: urn:iso:std:iso:3166
        code: US
        display: United States of America
copyrightYear: 2025
releaseLabel: ci-build
publisher:
  name: Andrew Rose LPC
  url: http://wrig.corisystem.org
parameters:
  path-suppressed-warnings: input/ignoreWarnings.txt
